### ISSUE TITLE
new theory scoping

### ISSUE THREAD

**Issue by jbs1** [OMdoc/OMDoc#215]
_migrated from Trac, where originally posted by **kohlhase** on 19-Mar-2009 2:46am_

spun off from #595

Another somewhat controversial change I need:

Every (sub-)theory should open a scope. The theory-constitutive elements theory, symbol, imports, and axiom should have name-attributes and be subject to name uniqueness within the scope (as opposed to xml:id uniqueness within the document).

Note that that list includes the theory element itself which may occur as a sub-theory. Only top-level theories would be identified by an xml:id.

The scope of a sub-theory should contain all symbol, imports, theory, and axiom names previously declared in the super-theory.

A symbol, import, axiom, or theory must be accessible by some path syntax. A path starts with the top-level theory, followed by the nested sub-theories, and ends with the name.

Open questions: Should it be allowed to shadow names in sub-theories? I say: No. Should a theory have one big scope, or 4 separate scopes for symbols, axioms, imports, and sub-theories? I am undecided.

**Comment by jbs1** [comment]
_migrated from Trac, where originally posted by **kohlhase** on 19-Mar-2009 2:46am_

@Florian, what is the state of this issue? Still valid?

**Comment by florian** [comment]
@jbs1 Please stop @ mentioning me as I get an email for every single one of these posts. You mean another Florian, with a different GitHub username.
